# Generated by Django 4.2.4 on 2023-08-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descriptions', models.TextField(max_length=500)),
                ('list_judge', models.ManyToManyField(related_name='Judges', to='profiles.judge')),
                ('list_participant', models.ManyToManyField(related_name='list_participant', to='profiles.participant')),
            ],
        ),
    ]
